### ISSUE TITLE
Sign In With GitHub fails

### ISSUE THREAD

**Issue by starkblaze01** [evermax/stargraph#4]
It responds with HTTP ERROR 500
![Screenshot from 2019-06-10 12-26-14](https://user-images.githubusercontent.com/22374162/59178046-7a439b00-8b7b-11e9-9e1e-eb0fad7f9c75.png)

**Comment by austinhuang0131** [comment]
Continues to fail but responds with error 502

**Comment by evermax** [comment]
I restarted the server but forget to bring the backend back up.

I need to work on fixing that issue by starting the service on boot but haven't gotten around to doing it yet.

Should be good now :)

Feel free to reopen if it happens again!
